# Stubs for pytsv.scripts.aggregate (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def main(folder, output_file, match_columns, aggregate_columns, do_unlink): ...
