# Stubs for pytsv.scripts.drop_duplicates_by_columns (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def main(progress, input_file, output_file, match_columns): ...
