# Stubs for pytsv.scripts.fix_columns (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def main(progress, input_file, output_file, fix_columns, clean_edges, sub_trailing, remove_non_ascii, lower_case, check_non_ascii): ...
