# Stubs for pytsv.scripts.histogram_by_column (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def main(input_file, output_file, column_number, bucket_number): ...
