# Stubs for pytsv.scripts.sample_by_column (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def main(factor_column, sample_columns, size, input_file, output_file): ...
